### ISSUE TITLE
Centering menu and notebook contents in browser

### ISSUE THREAD

**Issue by j1c** [neilpanchal/spinzero-jupyter-theme#1]
It seems like when using the theme, the menu and the contents of the notebooks are not centered, and is left justified. Could the theme be modified so that everything is centered in the browser?

Using:

- Chrome `Version 63.0.3239.132`
- Python `3.6`
- `jupyter==1.0.0`
- OSX `10.12.6 (16G1036)`

**Comment by pybokeh** [comment]
@j1c I am not a HTML/CSS expert, but the way I addressed this is I modified the custom.css file and in line 131, changed body's "left" parameter from 40px to something larger like 100px where it was originally:
```
body {
    background-color: #FFF !important;
    color: #828282;
    font-weight: normal;
    font-family: "sf-mono", "Helvetica Neue", Helvetica, Arial, sans-serif;
    overflow: inherit;
    right: auto;
    left: 40px;
}
```

I also increased the width by modifying the ".container" element's width parameter to something larger like 1200px where it was originally:
```
.container{
    width: 940px"
}
```

It will take a bit of trial and error until you find a setting to your liking.  I'm interested if there is a better way, but I hope this helps.

**Comment by j1c** [comment]
@pybokeh Thanks for the suggestion. I looked into centering the body, and it was an easy fix by changing the body. I deleted `right` and `left`, and put in `vertical-align: middle;`. Looks like this:

```
body {
    background-color: #FFF !important;
    color: #828282;
    font-weight: normal;
    font-family: "sf-mono", "Helvetica Neue", Helvetica, Arial, sans-serif;
    overflow: inherit;
    vertical-align: middle;
}
```

**Comment by neilpanchal** [comment]
@pybokeh @j1c Left justification was done on purpose, but now I am having second thoughts. I think center justification is cleaner since the main container is constant width. I'll add your changes to the main repository!

Thank you for the suggestions.

**Comment by pybokeh** [comment]
@j1c "vertical-align"?  Hmm, I would expect it to be something like "horizontal-align", since my understanding is you want the body to be centered along the horizontal axis.

**Comment by j1c** [comment]
@pybokeh You are right. I tried removing all lines for alignment, and seems to be horizontally aligned.

**Comment by pybokeh** [comment]
@j1c Ahh thanks for the clarification!  Phew!  I thought I had my horizontal and vertical mixed up for a second there ;-)

**Comment by neilpanchal** [comment]
@j1c @pybokeh Thank you, I've pulled the changes in master.
