### ISSUE TITLE
Getting codec error when downloading notebook as HTML

### ISSUE THREAD

**Issue by pybokeh** [neilpanchal/spinzero-jupyter-theme#2]
I get this error message when I attempt to download the notebook as HTML:
nbconvert failed: 'charmap' codec can't decode byte 0x90 in position 5555: character maps to <undefined>

When I remove the reference to the custom CSS file, I don't get the error message.  So I'm pretty sure the error was caused by the custom CSS and pandoc's or nbconvert's inability to convert non-ASCII characters?

This is on Windows 7 machine at work and Python version 3.6.2.

**Comment by pybokeh** [comment]
OK I fixed by removing line 273 from the CSS file.  Apparently it has a comment that references Unicode arrows.   Hmm, I thought the code that does the conversion would graciously handle this situation or the event that there could be Unicode characters in the CSS file.  Oh well...

**Comment by pybokeh** [comment]
I can close this issue unless someone thinks I should reference this issue to the jupyter nbconvert/pandoc folks and see if they can make it so that during the conversion, this error can be handled more robustly.

**Comment by neilpanchal** [comment]
@pybokeh Thanks. :) Closed.
