### ISSUE TITLE
making a dark theme as an option for this?

### ISSUE THREAD

**Issue by shelper** [neilpanchal/spinzero-jupyter-theme#4]
would that be possible?

**Comment by neilpanchal** [comment]
@shelper I think the html and css would be fine. But the problem with dark jupyter themes (see [here](https://github.com/nsonnad/base16-ipython-notebook)) is that any plots you generate in the notebook will be white. If you use matplotlib, then it is a pain to generate black background plots and there are many issues with this approach. 

That said, if you're primarily writing code in notebooks, then it wouldn't be a bad idea. But, then I would just use something like a sublime text editor + jupyter notebook plugin.
