### ISSUE TITLE
Theme not transferred to html

### ISSUE THREAD

**Issue by parthi2929** [neilpanchal/spinzero-jupyter-theme#5]
Hi

This is great one for academic purposes., however the theme is not transferred when I export to html. The exported html looks ordinary only. Can you please check and fix??

**Comment by neilpanchal** [comment]
Exporting HTML, PDF, etc.. is done through nbconvert module. It has its own .css and theming aspects, but I am not 100% if they have user API. It is unfortunate that Jupyter doesn't transfer the custom styles to nbconvert.

Thanks for raising this but unfortunately, it is out of scope for this effort. If you find a way, please reopen this issue and share your findings.

**Comment by parthi2929** [comment]
Hi

I did find some that could help to make nbconvert use custom css. 

[nbconvert to html css formatting](https://github.com/ipython/ipython/issues/8537)  
[embed custom.css](https://github.com/jupyter/notebook/pull/185)  
[CSSHTMLHeaderPreprocessor ](https://github.com/jupyter/notebook/pull/241)  
[preprocessors](https://nbconvert.readthedocs.io/en/latest/api/preprocessors.html)
